// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://woydvjzscfgnczwzlbxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndveWR2anpzY2ZnbmN6d3psYnhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MTcxNTIsImV4cCI6MjA1NTI5MzE1Mn0.fldwSOvmeOTmAzguNUm8Q5drIwzcITUV3C-ddhUlG_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);